name: "✨ Feature request"
description: Suggest an idea for this project.
labels: ["Needs Investigation :mag:", "Feature :sparkles:"]
body:
- type: markdown
  attributes:
    value: |
      Thanks for suggesting new features or pointing our missing functionality.  
      Please describe your request in detail so we can understand your ideas. Feel free to upload additional material such as mockups, diagrams, or sketches.
- type: textarea
  attributes:
    label: Is your feature request related to a problem?
    description: Please describe. A clear and concise description of what the problem is.
    placeholder: Ex. I'm always frustrated when ...
- type: textarea
  attributes:
    label: Possible Solution
    description: Describe the solution you'd like.
  validations:
      required: true
- type: textarea
  attributes:
    label: Alternatives
    description: A clear and concise description of any alternative solutions or features you've considered.
- type: textarea
  attributes:
    label: Additional Context
    description: Add any other context or screenshots about the feature request here.
