name: "Test Clang Tidy"

on: [push, workflow_dispatch, pull_request] # Trigger for every push as well as for every pull request. Yes, this will run stuff twice in case we create a PR from inside this repo. I'm open for better solutions, where I do not have to specify each brach individually for the 'push' trigger.

jobs:
  clang-tidy:
    runs-on: ubuntu-latest
    container: fedora:latest
    steps:
    - name: Update package list
      run: sudo dnf update -y
    - name: Install dependencies
      run: sudo dnf install -y openssl-devel cmake git gcc clang ninja-build libpsl-devel meson
    - name: Install clang-tidy
      run: sudo dnf install -y clang-tools-extra
    - name: Checkout
      uses: actions/checkout@v3
    - name: "[Release g++] Build & Test"
      env:
        CPR_BUILD_TESTS: ON
      uses: ashutoshvarma/action-cmake-build@master
      with:
        build-dir: ${{github.workspace}}/build
        source-dir: ${{github.workspace}}
        cc: clang
        cxx: clang++
        build-type: Release
        run-test: false
        configure-options: -DCPR_ENABLE_LINTING=ON